# Docker compose file for the application.

version: '3'
services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    #command: "bundle exec foreman start -f Procfile -p 3000"
    #volumes:
      #- .:/srv/app
    ports:
      - 8081:8080
    links:
      - solr

  zookeeper:
    image: jplock/zookeeper
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"

  solr:
    build: ./solr
    ports:
     - "8983:8983"
    links:
      - zookeeper
    command: "bash -c '/opt/solr/bin/solr start -f -z zookeeper:2181 -Dbootstrap_confdir=/solr-config/index/conf'"

  solr-proxy:
    build: ./solr-proxy
    ports:
      - "8000:80"
    links:
      - solr

  init:
    build:
      context: ./ocr
      dockerfile: init/Dockerfile
    ports:
     - "8080:8080"
    links:
      - solr
      - zookeeper

  tika:
    image: logicalspark/docker-tikaserver
    ports:
      - "9998:9998"
