apiVersion: v1
kind: Service
metadata:
  name: {{ include "tika.fullname" . }}
  labels:
    {{- include "tika.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.port }}
      protocol: TCP
      name: tika-service-port
  selector:
    {{- include "tika.selectorLabels" . | nindent 4 }}
